#!/bin/bash

if [ -z $1 ]
then
	echo "Usage $0 <domain>"
	exit
fi

root_directory="/var/www/$1"
mkdir $root_directory
addgroup --force-badname $1
adduser --force-badname --home $root_directory --no-create-home --disabled-password $1
usermod -s /usr/lib/sftp-server $1
usermod -g $1 $1
chown $1 $root_directory
chgrp $1 $root_directory
chgrp -R $1 $root_directory
for directory in $root_directory; do
        find $directory -type d -exec chmod 751 '{}' \;
        find $directory -type f -exec chmod 640 '{}' \;
done

