#!/usr/bin/php
<?php

  define("SYSTEM_SENDMAIL", "/usr/sbin/sendmail");
  define("SYSTEM_SPAM_LEVEL", 6);

  class parseMail{

    private $email;
    private $lines;
    private $headers;
    private $message;

    function open($filename){
      $fd = fopen($filename, "r");
      while(!feof($fd)){
        $this->email .= fread($fd, 1024);
      }
      fclose($fd);
      $this->lines = explode("\n", $this->email);
    }

    function parse(){
      $splittingheaders = true;
      for($i=0; $i <= count($this->lines); $i++){
        if($splittingheaders){
          if($field = preg_match("/(.*?)(: )/", $this->lines[$i], $fieldmatch)){
            if(isset($this->headers[$fieldmatch[1]])){
              if(is_array($this->headers[$fieldmatch[1]])){
                $this->headers[$fieldmatch[1]][] = (preg_match("/^" . $fieldmatch[1] . ": (.*)/", $this->lines[$i], $valuematch)) ? $valuematch[1] : false;
              }
              else{
                $temp = $this->headers[$fieldmatch[1]];
                $this->headers[$fieldmatch[1]]   = array();
                $this->headers[$fieldmatch[1]][] = $temp;
              }
            }
            else{
              $this->headers[$fieldmatch[1]] = (preg_match("/^" . $fieldmatch[1] . ": (.*)/", $this->lines[$i], $valuematch)) ? $valuematch[1] : false;
            }
          }
        }
        else{
          $this->message .= $this->lines[$i]."\n";
        }
        if(trim($this->lines[$i] == "")){
          $splittingheaders = false;
        }
      }
    }
    
    function getHeader($headername){
      return (isset($this->headers[$headername])) ? $this->headers[$headername] : false;
    }
    
    function getHeaders(){
      return $this->headers;
    }
    
    function get(){
      return $this->email;
    }

    function getRecipients(){  
      return (preg_match_all("/[\._a-zA-Z0-9-]+@[\._a-zA-Z0-9-]+/i", $this->getHeader("To"), $recipients)) ? $recipients[0] : false;
    }

  }
  
  function getUserSpamScore($email){
    $dbLink = mysql_connect("localhost", "mail", "rockmail");
    mysql_select_db("mail", $dbLink);
    $result = mysql_query("SELECT spam_level FROM users WHERE email = '".$email."' LIMIT 1", $dbLink);
    return ($spamLevel = @mysql_result($result, 0, "spam_level")) ? $spamLevel : false;
  }


  function sendMail($isspam = false){
    $Options = "";
    for($i = 1; $i <= $_SERVER['argc']; $i++){
      $Options .= " ".$_SERVER['argv'][$i];  
    }
    if($isspam){
      exec(SYSTEM_SENDMAIL." spamd < /var/tmp/sasendmail.out.".getmypid(), $output, $returnValue);
    }
    else{
      exec(SYSTEM_SENDMAIL.$Options." < /var/tmp/sasendmail.out.".getmypid(), $output, $returnValue);
    }
    unlink("/var/tmp/sasendmail.out.".getmypid());
    exit($returnValue);
  }

  $Message = new parseMail();
  $Message->open("php://stdin");
  $Message->parse();
  
  if(file_put_contents("/var/tmp/sasendmail.out.".getmypid(), $Message->get())){
    
    if($Message->getHeader("X-Spam-Status")){
      if(preg_match("/score=([+-]?\\d*\\.\\d+)(?![-+0-9\\.])/", $Message->getHeader("X-Spam-Status"), $score)){
        $spamScore = $score[1];
      }
      else{
        // Could not determine the actual spam score, despite that a spam status header exists, Something is wrong
      }
    }
    else{
	// No spam header set at all
    }

    $threshhold = SYSTEM_SPAM_LEVEL;
    $triggered  = false;
    
    if($Recipients = $Message->getRecipients()){
      foreach($Recipients as $index => $recipient){
        if(($userSpamLevel = getUserSpamScore($recipient))){
          if($triggered){
            $threshhold = ($userSpamLevel > $threshhold) ? $userSpamLevel : $threshhold;
          }
          else{
            $threshhold = $userSpamLevel;
            $triggered = true;
          }          
        }
      }
      if($spamScore < $threshhold){
        // Send the damn e-mail already
        echo "Sending E-mail, User Level Filter = ".$triggered." spam score ".$spamScore." is less than ".$threshhold."\n";
        sendMail();
      }
      else{
        echo "Spam from ".$Message->getHeader("From")." sent to spamd with score of ".$spamScore;
        sendMail(true);
      }
    }
    else{
      // No Recipients... fuck it, delete the bitch.
    }
  }
  else{
    // We were not able to temporarily write the e-mail... we might lose it.
  }

?>
